### ISSUE TITLE
GasMeter Power has been removed

### ISSUE THREAD

**Issue by B-Hartley** [megakid/ha_hildebrand_glow_ihd_mqtt#11]
I think the GasMeter Power section has been removed from the MQTT feed.
(As it didn't make sense due to lack of live data).

```
2022-06-30 21:39:17 WARNING (MainThread) [homeassistant.components.rest.sensor] JSON result was not a dictionary or list with 0th element a dictionary
2022-06-30 21:39:18 ERROR (MainThread) [homeassistant.util.logging] Exception in mqtt_message_received when handling msg on 'glow/XXXXXXXXXXXX/SENSOR/gasmeter': '{"gasmeter":{"timestamp":"2022-06-30T20:38:50Z","energy":{"import":{"cumulative":8570.929,"day":0.000,"week":24.531,"month":282.630,"units":"kWh","cumulativevol":775.636,"cumulativevolunits":"m3","dayvol":0.000,"weekvol":24.531,"monthvol":282.630,"dayweekmonthvolunits":"kWh","mprn":"XXXXXXXXXXXX","supplier":"---","price":{"unitrate":0.06000,"standingcharge":0.15090}}}}}'
Traceback (most recent call last):
  File "/config/custom_components/hildebrand_glow_ihd/sensor.py", line 246, in mqtt_message_received
    updateGroup.process_update(message)
  File "/config/custom_components/hildebrand_glow_ihd/sensor.py", line 290, in process_update
    sensor.process_update(parsed_data)
  File "/config/custom_components/hildebrand_glow_ihd/sensor.py", line 324, in process_update
    new_value = self._func(mqtt_data)
  File "/config/custom_components/hildebrand_glow_ihd/sensor.py", line 213, in <lambda>
    "func": lambda js : js['gasmeter']['power']['value']
KeyError: 'power'
```

**Comment by robhawkes** [comment]
I believe this is related to the recent changes they made to the firmware (see https://github.com/megakid/ha_hildebrand_glow_ihd_mqtt/issues/10)

**Comment by B-Hartley** [comment]
Agreed.
I've just removed it from the sensor.py for now to stop the errors.

**Comment by megakid** [comment]
Thanks for this - I also got a firmware update today as describe in #10 - I am about to push a new version that fixes this.
